### ISSUE TITLE
Exception in frontend after using the exported mask element

### ISSUE THREAD

**Issue by wowawebdesign** [CPS-IT/TYPO3-mask_export#1]
I've done an export from a mask CE. Then I installed the generated extension in a TYPO3 7.6 without Mask and placed the new CE on a page. In the BE everything works, but in the FE I see an error.
![exception-mask_export](https://cloud.githubusercontent.com/assets/343511/16728370/32b65194-4766-11e6-910b-c5459757fdf5.png)

**Comment by IchHabRecht** [comment]
Would you mind to submit either your mask.json file or your extension?

**Comment by wowawebdesign** [comment]
[mask_vcard_0.1.0_201607111239.zip](https://github.com/CPS-IT/mask_export/files/356971/mask_vcard_0.1.0_201607111239.zip)

[mask.json.zip](https://github.com/CPS-IT/mask_export/files/356973/mask.json.zip)

**Comment by IchHabRecht** [comment]
Would you mind to test branch https://github.com/CPS-IT/mask_export/tree/inline-handling

**Comment by wowawebdesign** [comment]
Hm, if I use this version, there is no export tab in the Mask module.

**Comment by wowawebdesign** [comment]
Ok, it works! 
In my example I have an email field, in the generated fluidtemplate is:
f:link.page pageUid="{data.tx_maskvcard2_vcard_email}">{data.[tx_maskvcard2_vcard_email]}</f:link.page>

I think the braces [ ] are wrong?

**Comment by IchHabRecht** [comment]
Thanks for pointing this out. Should be fixed in the pull request now.

**Comment by wowawebdesign** [comment]
No error in the latest inline-handling branch. But I tried an mask element with IRRE in IRRE, and the generated extension shows no images in the frontend. There's a difference in the fluidtemplates for this element, but unfortunately I have no time to test it at the moment. In the zip is the mask.json and both template files.
[Archiv.zip](https://github.com/CPS-IT/TYPO3-mask_export/files/378133/Archiv.zip)

**Comment by wowawebdesign** [comment]
Found an little error in the generated Fluidtemplate:
<f:link.page pageUid="{data.tx_maskwowaexample_vcard_email}">{data.tx_maskwowaexample_vcard_email</f:link.page>

Missing } before closing </f:link.page>

**Comment by IchHabRecht** [comment]
Tested your json and the export. Works on my machine ;-) Can you try to delete all caches and retest the IRRE in IRRE testcase?

**Comment by IchHabRecht** [comment]
Corrected the link problem in inline-handling branch
