### ISSUE TITLE
Content Element Wizard TYPE: [ INVALID VALUE ]

### ISSUE THREAD

**Issue by marvinhuebner** [CPS-IT/TYPO3-mask_export#14]
Today i tested the mask_export extension and found a bug after i installed my generated template extension. 

In the content element wizard my new content element is available, but if i select it i receive the following error: `TYPE: [ INVALID VALUE ("maskexample_example_table") ]`. 

I’ve installed mask 2.1.1 and mask_export 0.3.1.

I advance i will sent you a zip file with my generated extension and the mask.json file via Slack, maybe this will help you.

**Comment by IchHabRecht** [comment]
Can you try the branch https://github.com/CPS-IT/TYPO3-mask_export/tree/fix-phpfilecollection

**Comment by marvinhuebner** [comment]
I've tested it and it works, great. Thanks!

But one other thing. I've seen that the Type in the select field is a little bit confusing and i can't explain why but the know the gridelements are unter the type _maskexample_.

<img width="378" alt="cursor_und_typo3_dev__typo3_cms_7_6_10_" src="https://cloud.githubusercontent.com/assets/13386633/18338279/c7fb03c6-7597-11e6-8e2e-cb736ac80282.png">

**Comment by IchHabRecht** [comment]
That is the correct behavior of the core. Unfortunately there isn't any good way to handle groups and items for select fields. As gridelements is loaded after your mask_example extension it is added at the end of the select items.

**Comment by marvinhuebner** [comment]
Ok i understand.
