### ISSUE TITLE
Recommended Workflow

### ISSUE THREAD

**Issue by ursbraem** [CPS-IT/TYPO3-mask_export#16]
I saw someone thought this was an import-export addon for mask (like I did too at first) but it's different. Very interesting!!

So I have a few questions:

Am I right that it's rather like a kickstarter to replace the manual coding of new field types, using mask as a GUI engine?

Would you install mask in some independent TYPO3 instance and generate the export(s) from there? Or just run both extensions (mask and mymaskexport) in the same "target" site?

Is there stuff that mask does that won't run if I run just the export and not mask?

Or did I get it all wrong? :-)

**Comment by IchHabRecht** [comment]
Hi Urs,

> Am I right that it's rather like a kickstarter to replace the manual coding of new field types, using mask as a GUI engine?

Yes, that is true. IMHO generating content elements with the mask wizard is currently the best way to generate own content elements.

> Would you install mask in some independent TYPO3 instance and generate the export(s) from there? Or just run both extensions (mask and mymaskexport) in the same "target" site?

That target of the extension was always to be able to use the mask wizard but to not use it in production systems. So I recommend to install mask in a local system and use the export to have your content elements in VCS.

> Is there stuff that mask does that won't run if I run just the export and not mask?

One know thing are the labels for content elements. In mask it is possible to define different labels for the same field in different content elements. In the export only one label is stored in the language file, but of course that can be changed afterwards in the export.

**Comment by ursbraem** [comment]
Thanks Nicole for the clarification! As it's still in an early stage, I'd propose a renaming into something like content_builder (with mask as a dependency). While I fully understand if you don't want to do it :-) .. I also think powermail should be called powerforms...

**Comment by IchHabRecht** [comment]
As this extension is based on what mask does, it will stick to the name. IMHO it should be clear that an export exports something. And the description says it will export your content elements as extension.

**Comment by ursbraem** [comment]
Sure
