### ISSUE TITLE
in some places the name of the generated extension gets confused

### ISSUE THREAD

**Issue by pi-phi** [CPS-IT/TYPO3-mask_export#20]
I wanted to export the extension with the name 'test_mask_export'. 
that name is used but each time when a file is referenced with EXT:<extensionname> the extension name is written as 'test_test_mask_export_export'.

**Comment by IchHabRecht** [comment]
Hi!

Thank you for your request. Would you mind to test the branch https://github.com/CPS-IT/TYPO3-mask_export/tree/fix-extension-replacement for your scenario? This should solve the problem of multiple replacement of the extension key.
