### ISSUE TITLE
Error Download

### ISSUE THREAD

**Issue by stefan1242** [CPS-IT/TYPO3-mask_export#22]
PHP Warning: ZipArchive::open(): Empty string as source in /Applications/XAMPP/xamppfiles/htdocs/list-engeneering/typo3conf/ext/mask_export/Classes/Controller/ExportController.php line 104

[mask.json.zip](https://github.com/CPS-IT/TYPO3-mask_export/files/510485/mask.json.zip)

**Comment by IchHabRecht** [comment]
Hi Stefan,

With the provided mask.json and the latest version of mask_export, I unfortunately don't get any warning. Do you see any empty file and/or filename in the provided file list before you download the extension? Which extension key are you using?

**Comment by stefan1242** [comment]
ext_icon.png is empty... Is this the problem?

**Comment by IchHabRecht** [comment]
Hi Stefan,

No, this isn't the problem. The icon's code cannot be displayed but is saved. The error message indicates an empty file name. Maybe there is a problem with the extension key you chose and its replacements.

**Comment by stefan1242** [comment]
it works, i could not reproduce it :) i have tested it with other elements... 👍

**Comment by IchHabRecht** [comment]
So I'm closing this issue then :-)
