### ISSUE TITLE
Can't display inline elements 

### ISSUE THREAD

**Issue by inawidmer** [CPS-IT/TYPO3-mask_export#23]
Hi,

TYPO3 7.6.4
mask 2.1.1
mask_export 0.4.0

I created a linklist in mask with a repeating element for the links.  

![mask_element](https://cloud.githubusercontent.com/assets/22655410/19145115/a9187084-8bad-11e6-8680-8748940c9a3a.PNG)

When I use the exported content element and create multiple inline elements, the inline elements will not be displayed in the frontend.

![exbase_varable_dump](https://cloud.githubusercontent.com/assets/18529499/19144787/cdf69806-8bab-11e6-9c10-cbba1421963a.PNG)

[mask_example_linklist_0.1.0_201610060927.zip](https://github.com/CPS-IT/TYPO3-mask_export/files/513151/mask_example_linklist_0.1.0_201610060927.zip)

[mask_json.zip](https://github.com/CPS-IT/TYPO3-mask_export/files/513161/mask_json.zip)

**Comment by IchHabRecht** [comment]
Hi Ina.

Thank you for your bug report. I tested the mask.json file you provided and exported the extension. After adding the TypoScript template and creating some links in the backend everything is shown as expected. 
![2016-10-06_203155](https://cloud.githubusercontent.com/assets/1453345/19165421/fdb86238-8c03-11e6-870b-629cad662e9b.jpg)
![2016-10-06_203245](https://cloud.githubusercontent.com/assets/1453345/19165435/0fc0d776-8c04-11e6-8b10-c1dad370e38f.jpg)

Can you please check you added the extension's TypoScript to your template record and you haven't changed it? It should provided the needed data processing out of the box.
Are there any other errors popping up while the frontend is generated?

**Comment by stucki** [comment]
Hi Nicole! We found the cause for the problem, see https://github.com/Gernott/mask/pull/45

Explanation: Our test site did not use "config.sys_language_overlay=1", which causes records with sys_language_uid=-1 ([All]) to be ignored.

The bug is most likely caused by EXT:mask which doesn't set the proper default value.

Thanks for you help and trying to solve this. As it looks like, there are no changes needed in EXT:mask_export.

**Comment by IchHabRecht** [comment]
I would recommend to change the generated TypoScript to your needs:

`
tt_content.maskexamplelinklist_linklist = FLUIDTEMPLATE
tt_content.maskexamplelinklist_linklist {
    file = EXT:mask_example_linklist/Resources/Private/Templates/TtContent/linklist.html
    dataProcessing.10 = TYPO3\CMS\Frontend\DataProcessing\DatabaseQueryProcessor
    dataProcessing.10 {
        if.isTrue.field = tx_maskexamplelinklist_links
        table = tx_maskexamplelinklist_links
        pidInList.field = pid
        where = parentid=###uid### AND sys_language_uid IN (###language###, -1) AND deleted=0 AND hidden=0 AND 1=1
        languageField = 0
        markers {
            uid.field = uid
            language.field = sys_language_uid
        }
        as = data_tx_maskexamplelinklist_links
    }
}
`

See the change in the where clause and the added language configuration.
