### ISSUE TITLE
prepare database changes for exported extension

### ISSUE THREAD

**Issue by pi-phi** [CPS-IT/TYPO3-mask_export#27]
After exporting the CE definitions as own extension and installing this extension you can not use any CEs which are created with the pure mask definition as there are a lot of places where the extension name is used. In mask you have `mask_*` or `tx_mask_*`, in the export you have your (unified) extension key.

this occurs for:
- new tables
- new fields (in tt_content and new tables)
- entries in the field tt_content.CType

it would be nice to have a prepared update query which can change existing mask content to the new extension content.

**Comment by IchHabRecht** [comment]
Hi!

Thank you for your report. If you need to move existing elements to another TYPO3 system, you can simply name your extension mask. IMHO that should work. As I think exporting the configuration to an own extension after the usage of mask in the system is no popular use case, I don't want to blow up the exported extension. But thank you for letting me know.

**Comment by IchHabRecht** [comment]
As there was no reaction, I'm closing this issue. Please feel free to open a new request.
