### ISSUE TITLE
Sorting of IRRE-elements

### ISSUE THREAD

**Issue by chrimath** [CPS-IT/TYPO3-mask_export#29]
Backend sorting is ignored in frontend output of IRRE-elements.
Manually adding "orderBy = sorting" in TypoScript configuration of content elements (in "dataProcessing"-section) fixes this. This should be added automatically when exporting mask-elements via mask_export.

**Comment by IchHabRecht** [comment]
Hi Christian,

Thank you for your bug report. Would you mind to test the patch https://github.com/CPS-IT/TYPO3-mask_export/pull/30 (https://github.com/CPS-IT/TYPO3-mask_export/tree/fix-irre-sorting)?

**Comment by chrimath** [comment]
Hi Nicole,

thanks for creating a patch this fast! Tested it several times, with different mask elements. 
Seems to work.
