### ISSUE TITLE
Colpos 999 for nested content isn't allowed

### ISSUE THREAD

**Issue by ayacoo** [CPS-IT/TYPO3-mask_export#31]
I create a mask element with an option "Content" and link to another Mask Element (IRRE functionality) And i have three columns at the backend layout, too.

You can see it here: https://picload.org/image/rdwopggo/mask.png

After the export i deinstall mask and install mask_example extension with all mask elements and get this output: https://picload.org/image/rdwopgro/mask2.png

Hint: Extensions mask adds the colPos 999 via itemsProcFunc: mask\Classes\ItemsProcFuncs\ColPosList.php

**Comment by IchHabRecht** [comment]
Hi ayacoo,

Would you mind to test branch https://github.com/CPS-IT/TYPO3-mask_export/tree/nested-content-colpos for the fix.

Thank you.

**Comment by ayacoo** [comment]
Hi IchHabRecht,

works fine. Thank you :-)
