### ISSUE TITLE
localisation: translated elements: original element is shown in fe

### ISSUE THREAD

**Issue by blueamerican** [CPS-IT/TYPO3-mask_export#38]
when translating a content element created with a mask_export element, in the first language not the translated element is shown in fe, but the original element.

The element has only one repeatable element with three elements included.

in the backend everything seems to be ok.

if i reproduce this with the original mask extension it works.

version 0.4.2

**Comment by IchHabRecht** [comment]
Hi Markus,

I can't verify your problem in my demo installation and need more information about your system. If you don't mind, please attach your mask.json and your TypoScript configuration (language handling configuration).

Thank you for your feedback.

**Comment by blueamerican** [comment]
what do you mean with mask.json?    

language settings
#################
sys_language_uid = 0
    sys_language_overlay = 1
    language = de
    locale_all = de_DE.UTF-8
    htmlTag_setParams = lang="de" dir="ltr" class="no-js"

[globalVar = GP:L = 1]
    config {
        sys_language_uid = 1
        language = en
        locale_all = en_US.UTF-8
        htmlTag_setParams = lang="en" dir="ltr" class="no-js"
    }
[global]

System
##############
TYPO3 7.6.14
mask 2.1.1
mask_export 0.4.2

**Comment by IchHabRecht** [comment]
Hi Markus,

You should see a mask.json file in your typo3conf folder in your TYPO3 installation. Do you mind to provide this file? 

What is your configuration of config.sys_language_mode and config.sys_language_overlay?

**Comment by blueamerican** [comment]
[mask.zip](https://github.com/CPS-IT/TYPO3-mask_export/files/650254/mask.zip)

**Comment by blueamerican** [comment]
config.sys_language_overlay = 1
config.sys_language_mode is not set, maybe this is a reason?

**Comment by IchHabRecht** [comment]
I will investigate in the next few days. Thanks for providing those information.

**Comment by blueamerican** [comment]
after removing 
sys_language_overlay = 1
from my config, i can see the correct english content now.

but the original content is now not shown because ist is set to language "ALL".
see screen
![linklist](https://cloud.githubusercontent.com/assets/5647051/21172102/41796a56-c1d0-11e6-9ed9-923d008fbb38.png)

**Comment by IchHabRecht** [comment]
You shouldn't adjust config.sys_language_overlay but the TypoScript of the export as mentioned in https://github.com/CPS-IT/TYPO3-mask_export/issues/23#issuecomment-253740480 (see where clause and markers).

**Comment by blueamerican** [comment]
ok it worked
