### ISSUE TITLE
localisation: translation of a content element also fails

### ISSUE THREAD

**Issue by blueamerican** [CPS-IT/TYPO3-mask_export#39]
when translating a content element, which has a only a content field (where another content element is nested e,g, with a normal field, e.g. string), i get NO output in the fe in the new language.

in be everything is ok.

if i reproduce this with the original mask extension it works.

**Comment by IchHabRecht** [comment]
Hi Markus,

does this solution help you https://github.com/CPS-IT/TYPO3-mask_export/issues/23

**Comment by blueamerican** [comment]
yes this helped.
after removing
sys_language_overlay = 1
from my config it works.

but in 
https://github.com/CPS-IT/TYPO3-mask_export/issues/38

there is now a new problem
