### ISSUE TITLE
FR: Provide fields for Template-/Partial-/LayoutPaths

### ISSUE THREAD

**Issue by manuelbachl** [CPS-IT/TYPO3-mask_export#41]
Hi Nicole,

it would be great to have three more fields in your code export for defining the Template- Partial- and LayoutPaths. For now I have to set them manually for each generated and exported content element. When I don't set them, the Layouts would be searched in a wrong path below `ext_folder/Resources/Private/Templates/TtContent/Templates`

my workaround is this:

```
tt_content.websitetemplate_calltoaction = FLUIDTEMPLATE
tt_content.websitetemplate_calltoaction {
	layoutRootPath = {$styles.templates.layoutRootPath}
	partialRootPath = {$styles.templates.partialRootPath}
	templateRootPath = {$styles.templates.templateRootPath}
	file = EXT:website_template/Resources/Private/Templates/TtContent/calltoaction.html
}
```

with having defined `{$styles.templates.layoutRootPath}` in my constants. But I have to put those three lines manually into each Content element.

Well, would be great, to have this feature implemented - or any hint what I'm possibly doing wrong?

**Comment by manuelbachl** [comment]
Hehe and it would be great to have those fields stored like in #40 , too ;-)

**Comment by IchHabRecht** [comment]
I won't provide input fields for that but will add the default extension folders to the FLUIDTEMPLATE configuration. If you need some adjustments you should change those or rethink your template structure.

**Comment by IchHabRecht** [comment]
Hi Manuel,

would you mind to test the branch https://github.com/CPS-IT/TYPO3-mask_export/tree/set-fluid-paths-for-content-elements

Thank you very much.

**Comment by manuelbachl** [comment]
Hi Nicole, I'm sorry, I didn't got notified about your mention... But thanks for implementing both Features. I'll use it this Weekend I think
