### ISSUE TITLE
inconsistent export code after deleting content elements

### ISSUE THREAD

**Issue by blueamerican** [CPS-IT/TYPO3-mask_export#42]
[mask.zip](https://github.com/CPS-IT/TYPO3-mask_export/files/656763/mask.zip)
after deleting some content elements in mask, i want to export a new content element:

there i see some very strange code with already deleted fields.

e.G.:
ext_tables:

```
<?php
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::allowTableOnStandardPages('teaser_undefined');
```

in this table elements which are already deletet reoccur:

ext_tables.sql:

```
CREATE TABLE teaser_undefined (
...
    teaser_link tinytext,
    teaser_class tinytext,
    teaser_title tinytext,

```
these field do not exit any longer, but they are still in the exported code.

Even if i delete all content elements in mask.

TYPO3 7.6.14
mask 2.1.1
mask_export 0.4.2

**Comment by blueamerican** [comment]
[mask.zip](https://github.com/CPS-IT/TYPO3-mask_export/files/656765/mask.zip)

**Comment by IchHabRecht** [comment]
Hi Markus,

Thank you for providing the mask.json file. Unfortunately this issue belongs to mask itself as the extension doesn't delete those information in its json file. The export doesn't validate this file, it relies on its information. There is an issue already in masks bug tracker (https://forge.typo3.org/issues/79011)

Thank you very much.

**Comment by blueamerican** [comment]
ok, i delete the information manually.
