### ISSUE TITLE
[BUG] Missing subdirectory in backend preview path

### ISSUE THREAD

**Issue by manuelbachl** [CPS-IT/TYPO3-mask_export#49]
in `TYPO3-mask_export/Classes/Aggregate/BackendPreviewAggregate.php` on line 140 there is missing `Content/`

but would be nice to have this userdefined aswell, but for now adding `Content/`should work fine.

**Comment by IchHabRecht** [comment]
Sorry, haven't seen your pull request before. Would you mind to test https://github.com/CPS-IT/TYPO3-mask_export/tree/correct-backend-preview-template-paths

**Comment by manuelbachl** [comment]
Tested, works now!
