### ISSUE TITLE
How to access nested file-element in backend preview?

### ISSUE THREAD

**Issue by manuelbachl** [CPS-IT/TYPO3-mask_export#55]
Hi there,

I'm building a backend preview with mask_export atm. Everything works fine for me but I really don't get this thing working:

I have some containers (for builing multicolumn layouts) with the possibility to add some other content elements. With fields like input, select, link and others, everything works fine. But I have also an element which uses the file-field. How can I use the processed data from this field inside a container (content field)? For testing purposes I have attached my mask.json (weird, that github won't let me upload a json-file, so I've zipped it).

My aim is to render the columns and inside them the selected images. If more files (e.g. the backend preview templates and partials) are needed, let me know.

Thanks in advance for your help

[mask.json.zip](https://github.com/CPS-IT/TYPO3-mask_export/files/733616/mask.json.zip)

**Comment by IchHabRecht** [comment]
With the new PR #62 you can access your sys_file_reference uid with {processedRow.tx_maskcontainer_containercontent1.0.tx_maskcontainer_image.0.uid} (please use your proper extension key for 'maskcontainer')
