### ISSUE TITLE
locallang_db.xlf missing

### ISSUE THREAD

**Issue by marcoseiler** [CPS-IT/TYPO3-mask_export#6]
In the generated extension, the file "locallang_db.xlf" seems to be missing. References to labels are in the generated TCA.
Only the file "locallang_db_new_content_el.xlf" with title and description for the new content elenents is there.

**Comment by IchHabRecht** [comment]
Do you see the locallang_db.xlf in the output of the module? Can you provide your mask.json? I don't have that problem in my test installation here.

**Comment by marcoseiler** [comment]
It's also missing in the output of the module.
Here's my mask.json (I suffixed it with .txt to attach it here). 
[mask.json.txt](https://github.com/CPS-IT/TYPO3-mask_export/files/404117/mask.json.txt)

**Comment by IchHabRecht** [comment]
Can you test the pull request https://github.com/CPS-IT/TYPO3-mask_export/pull/7

**Comment by marcoseiler** [comment]
Looks good, thank you! locallang_db.xlf is in place now and labels are (partially) available.
I found two other problems, and will open new issues soon.
