### ISSUE TITLE
Error with TYPO3 8.7

### ISSUE THREAD

**Issue by devtroll** [CPS-IT/TYPO3-mask_export#70]
Hello,

the following error occurred with the current TYPO3 Version 8.7:

`Oops, an error occurred! Argument 2 passed to CPSIT\MaskExport\Aggregate\ContentRenderingAggregate::addDataProcessing() must be of the type array, null given, called in typo3conf/ext/mask_export/Classes/Aggregate/ContentRenderingAggregate.php on line 141`

Can u find and fix that problem ?

Thanks !

P.S. Great Extension.

**Comment by IchHabRecht** [comment]
Hi Heiko,

For any kind of analysis I need some more information. Which version of mask and mask_export are you using? Which version of TYPO3 are you using (as 8.7 isn't released yet).

Would you mind to attach your mask.json and let me know which extension name you chose?

Thank you very much for your help.

**Comment by devtroll** [comment]
Hi,

ops, I mean TYPO3 Version 8.6.1. 

Version-Overview:

- Mask: 2.1.1
- Mask Export: 0.6.3

Hope you can help, because you have always right :)

Greetings.

**Comment by IchHabRecht** [comment]
Hi Heiko,

Would you mind to test the current version 0.7.0 of mask_export and/or provide the additional information I asked for?

**Comment by devtroll** [comment]
Hi,

same error, another line:

`Argument 2 passed to CPSIT\MaskExport\Aggregate\ContentRenderingAggregate::addDataProcessing() must be of the type array, null given, called in /typo3conf/ext/mask_export/Classes/Aggregate/ContentRenderingAggregate.php on line 155`

**Comment by IchHabRecht** [comment]
Could you tell me anything about your mask elements? It is quite hard to not be able to see your elements to find the error.

**Comment by IchHabRecht** [comment]
Hi Heiko,

do you have mask elements without any field in your configuration? Is this on purpose?

**Comment by dthuesing** [comment]
I am getting almost the same error with Typo3 7.6.15.

Any solutions yet?

<img width="862" alt="bildschirmfoto 2017-04-06 um 15 37 06" src="https://cloud.githubusercontent.com/assets/23642090/24757326/2e144dc4-1adf-11e7-9f51-0c07c5ab1363.png">

**Comment by IchHabRecht** [comment]
Hi dthuesing,

Maybe you can answer my question and/or send me your mask.json file? Otherwise I'm really unable to help with this problem.

**Comment by dthuesing** [comment]
[mask.json.pdf](https://github.com/CPS-IT/TYPO3-mask_export/files/902769/mask.json.pdf)

Thanks for your help :)

**Comment by devtroll** [comment]
Hello,

I have mask elements without field configuration.

Do u think that there is the problem ?

- send from mobile -

**Comment by IchHabRecht** [comment]
dthuesing,

Thanks for providing your mask.json. I'm now able to confirm the problem.

**Comment by IchHabRecht** [comment]
Hi devtroll,
hi dthuesing,

Would you mind to test https://github.com/CPS-IT/TYPO3-mask_export/pull/74 - thanks in advanced.
