### ISSUE TITLE
Inconsistent allocation in new content element wizard and type dropdown

### ISSUE THREAD

**Issue by marcoseiler** [CPS-IT/TYPO3-mask_export#9]
In the new content element wizard, the created content elements are added to  "Typical page content". In the type dropdown inside the content element, they are filed under "Forms".

**Comment by IchHabRecht** [comment]
In fact this is the same behavior in mask without the export. Will see if I can find some solution for that.

**Comment by marcoseiler** [comment]
I see, this seems to be a more general problem.

**Comment by IchHabRecht** [comment]
You might want to check out the attached patch. It's a simple solution for an own extension divider

**Comment by marcoseiler** [comment]
Now my content elements in the type dropdown are filed under _myextkey_. Nice.

**Comment by marcoseiler** [comment]
But, with this patch, the columns part of the TCA seems to be missing.

**Comment by IchHabRecht** [comment]
Can you explain, what you mean?

**Comment by IchHabRecht** [comment]
Found the problem - would you mind to re-try?

**Comment by marcoseiler** [comment]
Can't see your changes, sorry.

**Comment by IchHabRecht** [comment]
It's the same branch

**Comment by marcoseiler** [comment]
It says: Latest commit 200d050  23 hours ago

**Comment by IchHabRecht** [comment]
Yes. I force-pushed it

**Comment by marcoseiler** [comment]
Changes in the same file? Because if I take the whole branch, the locallang_db file is missing.

**Comment by IchHabRecht** [comment]
switched from addPhpFile to appendPhpFile function in line 82

**Comment by marcoseiler** [comment]
Looks good now. 
TCA columns in place and new content elements separated in type dropdown.
